# Generated by Django 5.1.5 on 2025-02-25 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight_declaration_operations', '0009_alter_flightdeclaration_type_of_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorRIDNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('message', models.TextField(help_text='Specify the message to be sent to the operator')),
                ('is_active', models.BooleanField(default=True, help_text='Specify if the notification is active, only active notifications will be sent to the operator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight_declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_declaration_operations.flightdeclaration')),
            ],
        ),
    ]
