FROM --platform=linux/amd64 python:3.12-slim

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1



WORKDIR /app
COPY requirements.txt /app/
RUN pip install -r requirements-dev.txt
RUN rm -rf __pycache__
COPY . /app/
