# Generated by Django 5.1.8 on 2025-05-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraint_operations', '0002_constraintdetail_delete_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraintreference',
            name='ovn',
            field=models.CharField(blank=True, help_text='Once the operational intent is created, the OVN is stored here.', max_length=128, null=True),
        ),
    ]
