# Generated by Django 5.1.8 on 2025-05-29 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraint_operations', '0006_compositeconstraint'),
        ('flight_declaration_operations', '0015_alter_flightoperationalintentreference_ovn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositeconstraint',
            name='declaration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_declaration_operations.flightdeclaration'),
        ),
    ]
