# Generated by Django 5.1.10 on 2025-06-10 13:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rid_operations', '0003_isasubscription_subscription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RIDFlightDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_description', models.TextField(blank=True, help_text='The operation description of the flight', null=True)),
                ('operator_location', models.TextField(blank=True, help_text='The operator location of the flight', null=True)),
                ('operator_id', models.CharField(blank=True, help_text='The operator ID of the flight, e.g., a UAS operator ID', max_length=255, null=True)),
                ('auth_data', models.CharField(blank=True, help_text='The authorization data of the flight, e.g., a UAS authorization ID', max_length=255, null=True)),
                ('uas_id', models.CharField(blank=True, help_text='The UAS ID of the flight, e.g., a UAS serial number', max_length=255, null=True)),
                ('eu_classification', models.CharField(blank=True, help_text='The EU classification of the flight, e.g., Open, Specific, Certified', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
