"""initial_tables

Revision ID: 214fa5d62bd1
Revises:
Create Date: 2026-05-30 14:34:45.178260

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "214fa5d62bd1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flight_declaration",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("operational_intent", sa.Text(), nullable=False),
        sa.Column("flight_declaration_raw_geojson", sa.Text(), nullable=True),
        sa.Column("type_of_operation", sa.Integer(), nullable=False),
        sa.Column("bounds", sa.String(length=140), nullable=False),
        sa.Column("aircraft_id", sa.String(length=256), nullable=False),
        sa.Column("state", sa.Integer(), nullable=False),
        sa.Column("originating_party", sa.String(length=100), nullable=False),
        sa.Column("submitted_by", sa.String(length=254), nullable=True),
        sa.Column("approved_by", sa.String(length=254), nullable=True),
        sa.Column("latest_telemetry_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("start_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "flight_feed_observation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("latitude_dd", sa.Float(), nullable=False),
        sa.Column("longitude_dd", sa.Float(), nullable=False),
        sa.Column("altitude_mm", sa.Float(), nullable=False),
        sa.Column("traffic_source", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.Integer(), nullable=False),
        sa.Column("icao_address", sa.Text(), nullable=False),
        sa.Column("metadata", sa.Text(), nullable=False),
        sa.Column("sensor_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_flight_feed_observation_created_at"), "flight_feed_observation", ["created_at"], unique=False)
    op.create_table(
        "flight_feed_signed_telemetry_public_key",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key_id", sa.Text(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "geo_fence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("raw_geo_fence", sa.Text(), nullable=True),
        sa.Column("geozone", sa.Text(), nullable=True),
        sa.Column("upper_limit", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("lower_limit", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("altitude_ref", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("bounds", sa.String(length=140), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(length=140), nullable=True),
        sa.Column("is_test_dataset", sa.Boolean(), nullable=False),
        sa.Column("start_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rid_flight_detail",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("operation_description", sa.Text(), nullable=True),
        sa.Column("operator_location", sa.Text(), nullable=True),
        sa.Column("operator_id", sa.String(length=256), nullable=True),
        sa.Column("auth_data", sa.Text(), nullable=True),
        sa.Column("uas_id", sa.Text(), nullable=True),
        sa.Column("eu_classification", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rid_isa_subscription",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.String(length=256), nullable=False),
        sa.Column("view", sa.String(length=256), nullable=False),
        sa.Column("flight_details", sa.Text(), nullable=False),
        sa.Column("end_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("view_hash", sa.String(length=64), nullable=False),
        sa.Column("is_simulated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "surveillance_heartbeat_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_on_time", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "surveillance_sensor",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sensor_type", sa.Integer(), nullable=False),
        sa.Column("sensor_identifier", sa.String(length=256), nullable=False),
        sa.Column("refresh_rate_seconds", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("horizontal_accuracy_m", sa.Float(), nullable=False),
        sa.Column("vertical_accuracy_m", sa.Float(), nullable=False),
        sa.Column("expected_latency_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sensor_identifier"),
    )
    op.create_table(
        "surveillance_session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "surveillance_track_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("had_active_tracks", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conformance_record",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("flight_declaration_id", sa.Uuid(), nullable=True),
        sa.Column("conformance_state", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("geofence_breach", sa.Boolean(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["flight_declaration_id"], ["flight_declaration.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "constraint_detail",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("geofence_id", sa.Uuid(), nullable=True),
        sa.Column("volumes", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["geofence_id"], ["geo_fence.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("geofence_id"),
    )
    op.create_table(
        "constraint_reference",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("flight_declaration_id", sa.Uuid(), nullable=True),
        sa.Column("geofence_id", sa.Uuid(), nullable=True),
        sa.Column("uss_availability", sa.String(length=40), nullable=False),
        sa.Column("ovn", sa.String(length=128), nullable=True),
        sa.Column("manager", sa.String(length=256), nullable=True),
        sa.Column("uss_base_url", sa.String(length=256), nullable=False),
        sa.Column("version", sa.String(length=256), nullable=False),
        sa.Column("time_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_live", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["flight_declaration_id"], ["flight_declaration.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["geofence_id"], ["geo_fence.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("geofence_id"),
    )
    op.create_table(
        "flight_operation_tracking",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("flight_declaration_id", sa.Uuid(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("deltas", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["flight_declaration_id"], ["flight_declaration.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "flight_operational_intent_detail",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("declaration_id", sa.Uuid(), nullable=False),
        sa.Column("volumes", sa.Text(), nullable=False),
        sa.Column("off_nominal_volumes", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("subscribers", sa.Text(), nullable=False),
        sa.Column("is_live", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["declaration_id"], ["flight_declaration.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("declaration_id"),
    )
    op.create_table(
        "flight_operational_intent_reference",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("declaration_id", sa.Uuid(), nullable=False),
        sa.Column("uss_availability", sa.String(length=256), nullable=False),
        sa.Column("ovn", sa.String(length=128), nullable=True),
        sa.Column("manager", sa.String(length=256), nullable=False),
        sa.Column("uss_base_url", sa.String(length=256), nullable=False),
        sa.Column("version", sa.String(length=256), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("time_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("subscription_id", sa.String(length=256), nullable=False),
        sa.Column("is_live", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["declaration_id"], ["flight_declaration.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("declaration_id"),
    )
    op.create_table(
        "operator_rid_notification",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.String(length=256), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("flight_declaration_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["flight_declaration_id"], ["flight_declaration.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "surveillance_sensor_failure_notification",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sensor_id", sa.Uuid(), nullable=False),
        sa.Column("previous_status", sa.String(length=12), nullable=False),
        sa.Column("new_status", sa.String(length=12), nullable=False),
        sa.Column("recovery_type", sa.String(length=12), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["sensor_id"], ["surveillance_sensor.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "surveillance_sensor_health",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sensor_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["sensor_id"], ["surveillance_sensor.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sensor_id"),
    )
    op.create_table(
        "surveillance_sensor_health_tracking",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sensor_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("recovery_type", sa.String(length=12), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["sensor_id"], ["surveillance_sensor.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "surveillance_sensor_maintenance",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sensor_id", sa.Uuid(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("planned_or_unplanned", sa.String(length=12), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["sensor_id"], ["surveillance_sensor.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sensor_id"),
    )
    op.create_table(
        "composite_constraint",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("declaration_id", sa.Uuid(), nullable=False),
        sa.Column("bounds", sa.String(length=140), nullable=False),
        sa.Column("start_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("alt_max", sa.Float(), nullable=False),
        sa.Column("alt_min", sa.Float(), nullable=False),
        sa.Column("constraint_reference_id", sa.Uuid(), nullable=False),
        sa.Column("constraint_detail_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["constraint_detail_id"], ["constraint_detail.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["constraint_reference_id"], ["constraint_reference.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["declaration_id"], ["flight_declaration.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "flight_subscriber",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("operational_intent_reference_id", sa.Uuid(), nullable=False),
        sa.Column("subscriptions", sa.Text(), nullable=False),
        sa.Column("uss_base_url", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["operational_intent_reference_id"], ["flight_operational_intent_reference.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flight_subscriber")
    op.drop_table("composite_constraint")
    op.drop_table("surveillance_sensor_maintenance")
    op.drop_table("surveillance_sensor_health_tracking")
    op.drop_table("surveillance_sensor_health")
    op.drop_table("surveillance_sensor_failure_notification")
    op.drop_table("operator_rid_notification")
    op.drop_table("flight_operational_intent_reference")
    op.drop_table("flight_operational_intent_detail")
    op.drop_table("flight_operation_tracking")
    op.drop_table("constraint_reference")
    op.drop_table("constraint_detail")
    op.drop_table("conformance_record")
    op.drop_table("surveillance_track_event")
    op.drop_table("surveillance_session")
    op.drop_table("surveillance_sensor")
    op.drop_table("surveillance_heartbeat_event")
    op.drop_table("rid_isa_subscription")
    op.drop_table("rid_flight_detail")
    op.drop_table("geo_fence")
    op.drop_table("flight_feed_signed_telemetry_public_key")
    op.drop_index(op.f("ix_flight_feed_observation_created_at"), table_name="flight_feed_observation")
    op.drop_table("flight_feed_observation")
    op.drop_table("flight_declaration")
    # ### end Alembic commands ###
