from typing import Any, Protocol, runtime_checkable

from flight_blender.constraint.data_definitions import (
    CompositeConstraintPayload,
    Constraint as ConstraintData,
    ConstraintDetails,
    ConstraintReference as ConstraintReferencePayload,
)


@runtime_checkable
class ConstraintRepository(Protocol):
    def check_constraint_id_exists(self, constraint_id: str) -> bool: ...
    def get_constraint_by_geofence(self, geofence: Any) -> Any: ...
    def check_constraint_reference_id_exists(self, constraint_reference_id: str) -> bool: ...
    def get_constraint_reference_by_id(self, constraint_reference_id: str) -> Any: ...
    def get_constraint_details(self, constraint_id: str) -> Any: ...
    def get_geofence_by_constraint_reference_id(self, constraint_reference_id: str) -> Any | None: ...
    def write_constraint_details(self, constraint_id: str, constraint: ConstraintData) -> bool: ...
    def write_constraint_reference_details(self, constraint: ConstraintData) -> bool: ...
    def create_or_update_composite_constraint(self, composite_constraint_payload: CompositeConstraintPayload) -> Any: ...
    def update_constraint_reference_ovn(self, constraint_reference: Any, ovn: str) -> bool: ...
    def create_or_update_constraint_detail(self, constraint: ConstraintDetails, geofence: Any) -> Any | None: ...
    def create_or_update_constraint_reference(self, constraint_reference: ConstraintReferencePayload, geofence: Any, flight_declaration: Any) -> Any | None: ...
