from datetime import datetime
from typing import Any, Protocol, runtime_checkable

from flight_blender.scd.data_definitions import FlightDeclarationCreationPayload
from flight_blender.scd.scd_data_definitions import (
    CompositeOperationalIntentPayload,
    OperationalIntentReferenceDSSResponse,
    OperationalIntentUSSDetails,
    PartialCreateOperationalIntentReference,
    SubscriberToNotify,
)


@runtime_checkable
class FlightDeclarationRepository(Protocol):
    # peer ops
    def get_peer_operational_intent_details_by_id(self, operational_intent_id: str) -> Any | None: ...
    def get_peer_operational_intent_reference_by_id(self, operational_intent_reference_id: str) -> Any | None: ...
    def create_or_update_peer_operational_intent_details(self, peer_operational_intent_id: str, operational_intent_details: OperationalIntentUSSDetails) -> Any | None: ...
    def create_or_update_peer_operational_intent_reference(self, peer_operational_intent_reference_id: str, peer_operational_intent_reference: OperationalIntentReferenceDSSResponse) -> Any | None: ...
    def create_or_update_peer_composite_operational_intent(self, operation_id: str, composite_operational_intent: CompositeOperationalIntentPayload) -> bool: ...
    def clear_stored_operational_intents(self) -> None: ...

    # flight declarations
    def get_all_flight_declarations(self) -> list: ...
    def check_flight_declaration_exists(self, flight_declaration_id: str) -> bool: ...
    def get_flight_declaration_by_id(self, flight_declaration_id: str) -> Any | None: ...
    def create_flight_declaration(self, flight_declaration_creation: FlightDeclarationCreationPayload) -> Any | None: ...
    def delete_flight_declaration(self, flight_declaration_id: str) -> bool: ...
    def set_flight_declaration_non_conforming(self, flight_declaration: Any) -> None: ...
    def check_flight_declaration_active(self, flight_declaration_id: str, now: datetime) -> bool: ...
    def check_active_activated_flights_exist(self) -> bool: ...
    def get_active_activated_flight_declarations(self) -> Any: ...
    def get_current_flight_accepted_activated_declaration_ids(self, now: str) -> Any: ...
    def update_telemetry_timestamp(self, flight_declaration_id: str) -> bool: ...
    def update_flight_operation_state(self, flight_declaration_id: str, state: int) -> bool: ...
    def update_flight_operation_operational_intent(self, flight_declaration_id: str, operational_intent: PartialCreateOperationalIntentReference) -> bool: ...

    # composite operational intents
    def check_composite_operational_intent_exists(self, flight_declaration_id: str) -> bool: ...
    def get_composite_operational_intent_by_declaration_id(self, flight_declaration_id: str) -> Any | None: ...
    def create_or_update_composite_operational_intent(self, flight_declaration: Any, composite_operational_intent_payload: Any) -> bool: ...

    # operational intent references
    def get_flight_operational_intent_reference_by_flight_declaration_id(self, flight_declaration_id: str) -> Any | None: ...
    def get_flight_operational_intent_reference_by_flight_declaration_obj(self, flight_declaration: Any) -> Any | None: ...
    def check_flight_operational_intent_reference_by_id_exists(self, operational_intent_ref_id: str) -> bool: ...
    def get_operational_intent_reference_by_id(self, operational_intent_ref_id: str) -> Any: ...
    def get_flight_operational_intent_reference_by_id(self, operational_intent_ref_id: str) -> Any | None: ...
    def update_flight_operational_intent_reference_ovn(self, flight_operational_intent_reference: Any, ovn: str) -> bool: ...
    def update_flight_operational_intent_reference_op_int(self, flight_operational_intent_reference: Any, dss_operational_intent_reference_id: str) -> bool: ...
    def update_flight_operational_intent_reference(self, flight_operational_intent_reference: Any, update_operational_intent_reference: OperationalIntentReferenceDSSResponse) -> bool: ...
    def update_flight_operational_intent_reference_op_int_ovn(self, flight_operational_intent_reference: Any, dss_operational_intent_reference_id: str, ovn: str) -> bool: ...
    def update_flight_operational_intent_reference_with_dss_response(self, flight_declaration: Any, dss_operational_intent_reference_id: str, ovn: str, dss_response: OperationalIntentReferenceDSSResponse) -> bool: ...
    def create_flight_operational_intent_reference_with_submitted_operational_intent(self, flight_declaration: Any, operational_intent_reference_payload: Any) -> Any | None: ...
    def create_flight_operational_intent_reference_from_flight_declaration_obj(self, flight_declaration: Any) -> bool: ...
    def create_flight_operational_intent_reference(self, flight_declaration: Any, created_operational_intent_reference: OperationalIntentReferenceDSSResponse) -> Any: ...

    # subscribers
    def get_subscribers_of_operational_intent_reference(self, flight_operational_intent_reference: Any) -> Any: ...
    def create_flight_operational_intent_reference_subscribers(self, flight_declaration: Any, subscribers: list[SubscriberToNotify]) -> bool: ...

    # operational intent details
    def check_flight_operational_intent_details_by_id_exists(self, operational_intent_ref_id: str) -> bool: ...
    def get_operational_intent_details_by_flight_declaration(self, flight_declaration: Any) -> Any | None: ...
    def get_operational_intent_details_by_flight_declaration_id(self, declaration_id: str) -> Any | None: ...
    def create_flight_operational_intent_details_with_submitted_operational_intent(self, flight_declaration: Any, operational_intent_details_payload: OperationalIntentUSSDetails) -> Any | None: ...
    def update_flight_operational_intent_details(self, flight_operational_intent_detail: Any, operational_intent_details: OperationalIntentUSSDetails) -> bool: ...
