from datetime import datetime
from typing import Any, Protocol, runtime_checkable

import arrow

from flight_blender.core.entities.flight_feed import SingleAirtrafficObservation


@runtime_checkable
class FlightFeedRepository(Protocol):
    """Async repository used by FastAPI handlers (``FlightFeedOperations``,
    ``SurveillanceOperations``).

    Concrete implementation: ``SQLAlchemyFlightFeedRepository`` in
    ``flight_blender.infrastructure.database.repositories.sa_flight_feed``.
    """

    async def get_flight_observations(self, after_datetime: arrow.Arrow) -> Any: ...
    async def get_recent_flight_observations(self, after_datetime: arrow.Arrow | datetime) -> Any: ...
    async def get_closest_flight_observation_for_now(self, now: arrow.Arrow) -> Any: ...
    async def get_flight_observations_by_session(self, session_id: str, after_datetime: arrow.Arrow) -> Any: ...
    async def get_all_flight_observations_in_window(self, start_time: datetime, end_time: datetime) -> Any: ...
    async def get_latest_flight_observation_by_session(self, session_id: str) -> Any | None: ...
    async def list_signed_telemetry_public_keys(self) -> Any: ...
    async def get_signed_telemetry_public_key(self, pk: Any) -> Any | None: ...
    async def create_signed_telemetry_public_key(self, key_id: str, url: str, is_active: bool = True) -> Any: ...
    async def update_signed_telemetry_public_key(self, pk: Any, **kwargs: Any) -> Any | None: ...
    async def delete_signed_telemetry_public_key(self, pk: Any) -> bool: ...
    async def get_active_signed_telemetry_public_keys(self) -> Any: ...
    async def check_flight_declaration_active(self, flight_declaration_id: str, now: datetime) -> bool: ...
    async def get_flight_declaration_by_id(self, flight_declaration_id: str) -> Any | None: ...


@runtime_checkable
class FlightFeedWriter(Protocol):
    """Async write-side surface used by ``FlightFeedOperations``."""

    async def write_flight_observation(self, single_observation: SingleAirtrafficObservation) -> bool: ...
    async def bulk_write_flight_observations(self, observations: list[SingleAirtrafficObservation]) -> bool: ...


@runtime_checkable
class FlightFeedTaskDispatcher(Protocol):
    def dispatch_observations(self, observations: list[dict]) -> None: ...
    def start_opensky_network_stream(self, view_port: str, session_id: str) -> None: ...
    def stream_rid_telemetry_data(self, rid_telemetry_observations: str) -> None: ...


@runtime_checkable
class TelemetryValidator(Protocol):
    def parse_validate_current_states(self, current_states: Any) -> list[Any]: ...
    def parse_validate_rid_details(self, rid_flight_details: Any) -> Any: ...
    def validate_flight_details_current_states_exist(self, flight: Any) -> bool: ...
    def validate_observation_key_exists(self, raw_request_data: Any) -> bool: ...


@runtime_checkable
class SyncFlightFeedReader(Protocol):
    """Sync read-side surface used by Celery tasks and ``ObservationReadOperations``.

    Concrete implementation: ``SyncDatabaseFacade`` in
    ``flight_blender.infrastructure.database.repositories.sync_facade``.
    """

    def get_flight_observations(self, after_datetime: Any) -> list[dict]: ...
    def get_closest_flight_observation_for_now(self, now: Any) -> list[Any]: ...
    def get_flight_observation_objects(self) -> list[dict]: ...
    def get_latest_flight_observation_by_session(self, session_id: str) -> Any | None: ...
    def get_temporal_flight_observations_by_session(self, session_id: str, after_datetime: Any) -> list[dict]: ...
    def get_active_rid_observations_for_view(self, start_time: Any, end_time: Any) -> Any: ...
    def get_active_rid_observations_for_session_between_interval(self, session_id: str, start_time: Any, end_time: Any) -> list[Any]: ...


@runtime_checkable
class SyncFlightFeedWriter(Protocol):
    """Sync write-side surface used by Celery tasks."""

    def write_flight_observation(self, single_observation: SingleAirtrafficObservation) -> bool: ...
    def bulk_write_flight_observations(self, observations: list[SingleAirtrafficObservation]) -> bool: ...
    def delete_all_flight_observations(self) -> bool: ...
