from datetime import datetime
from typing import Any, Protocol, runtime_checkable

import arrow

from flight_blender.flight_feed.data_definitions import SingleAirtrafficObservation


@runtime_checkable
class FlightFeedRepository(Protocol):
    def get_flight_observations(self, after_datetime: arrow.Arrow) -> Any: ...
    def get_closest_flight_observation_for_now(self, now: arrow.Arrow) -> Any: ...
    def get_flight_observation_objects(self) -> Any: ...
    def get_temporal_flight_observations_by_session(self, session_id: str, after_datetime: arrow.Arrow) -> Any: ...
    def get_flight_observations_by_session(self, session_id: str, after_datetime: arrow.Arrow) -> Any: ...
    def get_all_flight_observations_in_window(self, start_time: datetime, end_time: datetime) -> Any: ...
    def get_latest_flight_observation_by_session(self, session_id: str) -> Any | None: ...
    def get_active_rid_observations_for_view(self, start_time: datetime, end_time: datetime) -> Any | None: ...
    def get_active_rid_observations_for_session(self, session_id: str) -> Any | None: ...
    def get_active_rid_observations_for_session_between_interval(self, start_time: datetime, end_time: datetime, session_id: str) -> Any | None: ...
    def bulk_write_flight_observations(self, observations: list[SingleAirtrafficObservation]) -> bool: ...
    def write_flight_observation(self, single_observation: SingleAirtrafficObservation) -> bool: ...
    def delete_all_flight_observations(self) -> bool: ...
