import uuid
from datetime import datetime
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class GeoFenceRepository(Protocol):
    async def get_geofences_by_date_range(self, start: datetime, end: datetime, is_test: bool = False) -> list[Any]: ...
    async def get_by_id(self, geofence_id: uuid.UUID) -> Any | None: ...
    async def create(self, **kwargs: Any) -> Any: ...
    async def delete(self, geofence_id: uuid.UUID) -> bool: ...
    async def get_test_geofences(self) -> list[Any]: ...
    async def delete_test_geofences(self) -> int: ...
    async def get_geospatial_data_sources(self, start: datetime, end: datetime) -> list[Any]: ...


@runtime_checkable
class GeoFenceTaskDispatcher(Protocol):
    def download_geozone_source(self, geo_zone_url: str, geozone_source_id: str) -> None: ...


@runtime_checkable
class GeoFenceSpatialService(Protocol):
    def filter_fences_by_viewport(self, fences: list[Any], viewport: list[float]) -> list[Any]: ...
    def has_intersection_at_position(self, fences: list[Any], longitude: float, latitude: float) -> bool: ...
