from typing import Any, Protocol, runtime_checkable
from uuid import UUID

from flight_blender.rid.rid_utils import RIDFlightDetails


@runtime_checkable
class RIDRepository(Protocol):
    def check_flight_details_exist(self, flight_detail_id: str) -> bool: ...
    def get_flight_details_by_id(self, flight_detail_id: str) -> Any: ...
    def get_rid_monitoring_task(self, session_id: UUID) -> Any | None: ...
    def check_rid_subscription_record_by_view_hash_exists(self, view_hash: int) -> bool: ...
    def check_rid_subscription_record_by_subscription_id_exists(self, subscription_id: str) -> bool: ...
    def get_rid_subscription_record_by_subscription_id(self, subscription_id: str) -> Any: ...
    def get_all_rid_simulated_subscription_records(self) -> Any: ...
    def get_rid_subscription_record_by_id(self, id: str) -> Any: ...
    def create_rid_subscription_record(
        self, subscription_id: str, record_id: str, view: str, view_hash: int, end_datetime: str, flights_dict: str, is_simulated: bool
    ) -> bool: ...
    def update_flight_details_in_rid_subscription_record(self, existing_subscription_record: Any, flights_dict: str) -> bool: ...
    def delete_all_simulated_rid_subscription_records(self) -> bool: ...
    def create_or_update_rid_flight_details(self, rid_flight_details_payload: RIDFlightDetails) -> Any: ...
    def delete_all_flight_details(self) -> bool: ...
    def create_rid_stream_monitoring_periodic_task(self, session_id: str, end_datetime: str) -> bool: ...
    def remove_rid_stream_monitoring_periodic_task(self, rid_stream_monitoring_task: Any) -> None: ...
