from datetime import datetime
from typing import Any, Protocol, runtime_checkable
from uuid import UUID


@runtime_checkable
class SurveillanceRepository(Protocol):
    def get_active_surveillance_sensors(self) -> Any: ...
    def get_surveillance_sensor_by_id(self, sensor_id: UUID) -> Any | None: ...
    def get_surveillance_session_by_id(self, surveillance_session_id: str) -> Any | None: ...
    def get_surveillance_periodic_tasks_by_session_id(self, surveillance_session_id: UUID | str) -> Any: ...
    def get_all_active_surveillance_sessions(self) -> Any: ...
    def get_surveillance_sessions_with_events_in_window(self, start_time: datetime, end_time: datetime) -> Any: ...
    def get_sensor_health_record(self, sensor_id: str) -> Any | None: ...
    def get_health_tracking_records_for_sensor(self, sensor_id: str, start_time: datetime, end_time: datetime) -> Any: ...
    def get_sensor_status_before_time(self, sensor_id: str, before_time: datetime) -> str | None: ...
    def get_heartbeat_events_in_window(self, start_time: datetime, end_time: datetime) -> Any: ...
    def get_heartbeat_events_for_session(self, surveillance_session_id: str, start_time: datetime, end_time: datetime) -> Any: ...
    def get_track_events_for_session(self, surveillance_session_id: str, start_time: datetime, end_time: datetime) -> Any: ...
    def get_failure_notifications_for_sensor(self, sensor_id: str, start_time: datetime, end_time: datetime) -> Any: ...
    def create_surveillance_session(self, surveillance_session_id: UUID | str, valid_until: str) -> bool: ...
    def create_surveillance_monitoring_heartbeat_periodic_task(self, surveillance_session_id: UUID | str) -> bool: ...
    def create_surveillance_monitoring_track_periodic_task(self, surveillance_session_id: str) -> bool: ...
    def remove_track_monitoring_heartbeat_periodic_task(self, track_monitoring_heartbeat_task: Any) -> None: ...
    def remove_surveillance_monitoring_heartbeat_periodic_task(self, surveillance_monitoring_heartbeat_task: Any) -> None: ...
    def delete_surveillance_session(self, surveillance_session_id: UUID | str) -> None: ...
    def update_sensor_health_status(self, sensor_id: str, new_status: str, recovery_type: str | None = None) -> bool: ...
    def record_heartbeat_event(self, surveillance_session_id: str, expected_at: datetime, delivered_on_time: bool) -> bool: ...
    def record_track_event(self, surveillance_session_id: str, expected_at: datetime, had_active_tracks: bool) -> bool: ...
