# Generated by Django 5.1.4 on 2025-01-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight_declaration_operations", "0008_alter_flightdeclaration_aircraft_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightdeclaration",
            name="type_of_operation",
            field=models.IntegerField(
                choices=[(1, "VLOS"), (2, "BVLOS"), (3, "CREWED")],
                default=1,
                help_text="At the moment, only Visual Line of Sight (VLOS) and Beyond Visual Line of Sight (BVLOS) operations are supported, for other types of operations, please issue a pull-request",
            ),
        ),
    ]
