# Generated by Django 5.1.5 on 2025-03-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_declaration_operations', '0009_alter_flightdeclaration_type_of_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightauthorization',
            name='ovn',
            field=models.CharField(blank=True, help_text='Once the operational intent is created, the OVN is stored here.', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='flightauthorization',
            name='dss_operational_intent_id',
            field=models.CharField(blank=True, help_text='Once the operational intent is shared on the DSS the operational intent is stored here. By default nothing is stored here.', max_length=36, null=True),
        ),
    ]
