# Generated by Django 5.1.5 on 2025-04-18 10:03

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight_declaration_operations", "0010_flightauthorization_ovn_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeerOperationalIntentDetail",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("volumes", models.TextField(blank=True)),
                ("off_nominal_volumes", models.TextField(blank=True)),
                ("priority", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_live", models.BooleanField(default=False, help_text="Set to true if the operational intent is live")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PeerOperationalIntentReference",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("uss_availability", models.CharField(max_length=256)),
                (
                    "ovn",
                    models.CharField(
                        blank=True, help_text="Once the operational intent is created, the OVN is stored here.", max_length=36, null=True
                    ),
                ),
                ("manager", models.CharField(max_length=256)),
                ("uss_base_url", models.CharField(help_text="USS base URL", max_length=256)),
                ("version", models.CharField(help_text="USS base URL", max_length=256)),
                ("state", models.CharField(max_length=40)),
                ("time_start", models.DateTimeField(default=datetime.datetime.now)),
                ("time_end", models.DateTimeField(default=datetime.datetime.now)),
                ("subscription_id", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_live", models.BooleanField(default=False, help_text="Set to true if the operational intent is live")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FlightOperationalIntentDetail",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("volumes", models.TextField(blank=True)),
                ("off_nominal_volumes", models.TextField(blank=True)),
                ("priority", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_live", models.BooleanField(default=False, help_text="Set to true if the operational intent is live")),
                (
                    "declaration",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="flight_declaration_operations.flightdeclaration"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FlightOperationalIntentReference",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("uss_availability", models.CharField(max_length=256)),
                (
                    "ovn",
                    models.CharField(
                        blank=True, help_text="Once the operational intent is created, the OVN is stored here.", max_length=36, null=True
                    ),
                ),
                ("manager", models.CharField(max_length=256)),
                ("uss_base_url", models.CharField(help_text="USS base URL", max_length=256)),
                ("version", models.CharField(help_text="USS base URL", max_length=256)),
                ("state", models.CharField(max_length=40)),
                ("time_start", models.DateTimeField(default=datetime.datetime.now)),
                ("time_end", models.DateTimeField(default=datetime.datetime.now)),
                ("subscription_id", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_live", models.BooleanField(default=False, help_text="Set to true if the operational intent is live")),
                (
                    "declaration",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="flight_declaration_operations.flightdeclaration"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompositeOperationalIntent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("bounds", models.CharField(max_length=140)),
                ("start_datetime", models.DateTimeField(default=datetime.datetime.now)),
                ("end_datetime", models.DateTimeField(default=datetime.datetime.now)),
                ("alt_max", models.FloatField()),
                ("alt_min", models.FloatField()),
                (
                    "declaration",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="flight_declaration_operations.flightdeclaration"),
                ),
                (
                    "operational_intent_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composite_operational_intent",
                        to="flight_declaration_operations.flightoperationalintentdetail",
                    ),
                ),
                (
                    "operational_intent_reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composite_operational_intent_reference",
                        to="flight_declaration_operations.flightoperationalintentreference",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FlightAuthorization",
        ),
    ]
