# Generated by Django 5.1.5 on 2025-04-18 14:39

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight_declaration_operations", "0011_peeroperationalintentdetail_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeerCompositeOperationalIntent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("bounds", models.CharField(max_length=140)),
                ("start_datetime", models.DateTimeField(default=datetime.datetime.now)),
                ("end_datetime", models.DateTimeField(default=datetime.datetime.now)),
                ("alt_max", models.FloatField()),
                ("alt_min", models.FloatField()),
                (
                    "operational_intent_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_composite_operational_intent",
                        to="flight_declaration_operations.peeroperationalintentdetail",
                    ),
                ),
                (
                    "operational_intent_reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_composite_operational_intent_reference",
                        to="flight_declaration_operations.peeroperationalintentreference",
                    ),
                ),
            ],
        ),
    ]
