# Generated by Django 5.1.5 on 2025-04-19 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_declaration_operations', '0012_peercompositeoperationalintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightoperationalintentdetail',
            name='subscribers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peeroperationalintentdetail',
            name='subscribers',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscriptions', models.TextField(blank=True)),
                ('uss_base_url', models.CharField(help_text='USS base URL', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operational_intent_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='flight_declaration_operations.flightoperationalintentreference')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
