# Generated by Django 5.1.5 on 2025-03-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight_feed_operations", "0003_alter_flightobeservation_traffic_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flightobeservation",
            name="timestamp",
        ),
        migrations.AlterField(
            model_name="flightobeservation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
