# Generated by Django 5.2.10 on 2026-04-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_feed_operations", "0007_alter_flightobservation_traffic_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightobservation",
            name="traffic_source",
            field=models.IntegerField(
                choices=[
                    (0, "1090ES"),
                    (1, "UAT"),
                    (2, "Multi-radar (MRT)"),
                    (3, "MLAT"),
                    (4, "SSR"),
                    (5, "PSR"),
                    (6, "Mode-S"),
                    (7, "MRT"),
                    (8, "SSR + PSR Fused"),
                    (9, "ADS-B"),
                    (10, "FLARM"),
                    (11, "Network Remote-ID"),
                    (12, "Other"),
                    (13, "Broadcast Remote-ID"),
                    (14, "ADS-L"),
                    (15, "Drone sensed by another means"),
                ],
                help_text="Source of the observation",
            ),
        ),
    ]
