# Generated by Django 5.2.10 on 2026-04-01 22:35

from django.db import connection, migrations, models


def add_sensor_timestamp_if_missing(apps, schema_editor):
    """Add sensor_timestamp column only if it doesn't already exist (idempotent)."""
    table = "flight_feed_operations_flightobservation"
    columns = [col.name for col in connection.introspection.get_table_description(connection.cursor(), table)]
    if "sensor_timestamp" not in columns:
        schema_editor.execute(
            'ALTER TABLE "flight_feed_operations_flightobservation" ADD COLUMN "sensor_timestamp" timestamp with time zone NULL'
        )


class Migration(migrations.Migration):

    dependencies = [
        ("flight_feed_operations", "0007_alter_flightobservation_traffic_source"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_sensor_timestamp_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="flightobservation",
                    name="sensor_timestamp",
                    field=models.DateTimeField(
                        blank=True,
                        help_text="Sensor-reported observation time (converted from unix epoch submitted by API client)",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="flightobservation",
            name="traffic_source",
            field=models.IntegerField(
                choices=[
                    (0, "1090ES"),
                    (1, "UAT"),
                    (2, "Multi-radar (MRT)"),
                    (3, "MLAT"),
                    (4, "SSR"),
                    (5, "PSR"),
                    (6, "Mode-S"),
                    (7, "MRT"),
                    (8, "SSR + PSR Fused"),
                    (9, "ADS-B"),
                    (10, "FLARM"),
                    (11, "Network Remote-ID"),
                    (12, "Other"),
                    (13, "Broadcast Remote-ID"),
                    (14, "ADS-L"),
                    (15, "Drone sensed by another means"),
                ],
                help_text="Source of the observation",
            ),
        ),
    ]
