# Generated by Django 5.2.10 on 2026-04-01 22:35

from django.db import migrations, models


def add_sensor_timestamp_if_missing(apps, schema_editor):
    """Add sensor_timestamp column only if it doesn't already exist (idempotent)."""
    flight_observation_model = apps.get_model("flight_feed_operations", "FlightObservation")
    table = flight_observation_model._meta.db_table
    db_connection = schema_editor.connection
    with db_connection.cursor() as cursor:
        columns = [col.name for col in db_connection.introspection.get_table_description(cursor, table)]

    if "sensor_timestamp" in columns:
        return

    sensor_timestamp_field = models.DateTimeField(
        blank=True,
        help_text="Sensor-reported observation time (converted from unix epoch submitted by API client)",
        null=True,
    )
    sensor_timestamp_field.set_attributes_from_name("sensor_timestamp")
    schema_editor.add_field(flight_observation_model, sensor_timestamp_field)


class Migration(migrations.Migration):
    dependencies = [
        ("flight_feed_operations", "0008_alter_flightobservation_traffic_source"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_sensor_timestamp_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="flightobservation",
                    name="sensor_timestamp",
                    field=models.DateTimeField(
                        blank=True,
                        help_text="Sensor-reported observation time (converted from unix epoch submitted by API client)",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="flightobservation",
            name="traffic_source",
            field=models.IntegerField(
                choices=[
                    (0, "1090ES"),
                    (1, "UAT"),
                    (2, "Multi-radar (MRT)"),
                    (3, "MLAT"),
                    (4, "SSR"),
                    (5, "PSR"),
                    (6, "Mode-S"),
                    (7, "MRT"),
                    (8, "SSR + PSR Fused"),
                    (9, "ADS-B"),
                    (10, "FLARM"),
                    (11, "Network Remote-ID"),
                    (12, "Other"),
                    (13, "Broadcast Remote-ID"),
                    (14, "ADS-L"),
                    (15, "Drone sensed by another means"),
                ],
                help_text="Source of the observation",
            ),
        ),
    ]
