# Generated by Django 5.2.10 on 2026-01-29 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance_monitoring_operations", "0002_surveillancesensor"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveillanceSensorHealth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("degraded", "Degraded"),
                            ("outage", "Outage"),
                        ],
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sensor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="surveillance_monitoring_operations.surveillancesensor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveillanceSensorMaintenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "planned_or_unplanned",
                    models.CharField(
                        choices=[("planned", "Planned"), ("unplanned", "Unplanned")],
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sensor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="surveillance_monitoring_operations.surveillancesensor",
                    ),
                ),
            ],
        ),
    ]
