# Generated by Django 5.2.10 on 2026-01-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "surveillance_monitoring_operations",
            "0003_surveillancesensorhealth_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="surveillancesensor",
            name="refresh_rate_seconds",
            field=models.FloatField(default=1.0),
        ),
    ]
