# Generated by Django 5.2.10 on 2026-02-20 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "surveillance_monitoring_operations",
            "0004_surveillancesensor_refresh_rate_seconds",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveillanceSensortHealthTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("degraded", "Degraded"),
                            ("outage", "Outage"),
                        ],
                        max_length=12,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now=True)),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_tracking_records",
                        to="surveillance_monitoring_operations.surveillancesensor",
                    ),
                ),
            ],
        ),
    ]
