# Generated by Django 5.2.10 on 2026-02-20 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "surveillance_monitoring_operations",
            "0005_surveillancesensorthealthtracking",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="surveillancesensor",
            name="expected_latency_ms",
            field=models.IntegerField(
                default=150,
                help_text="Expected average data delivery latency in milliseconds",
            ),
        ),
        migrations.AddField(
            model_name="surveillancesensor",
            name="horizontal_accuracy_m",
            field=models.FloatField(
                default=5.0, help_text="95th percentile horizontal accuracy in meters"
            ),
        ),
        migrations.AddField(
            model_name="surveillancesensor",
            name="vertical_accuracy_m",
            field=models.FloatField(
                default=5.0, help_text="95th percentile vertical accuracy in meters"
            ),
        ),
        migrations.AddField(
            model_name="surveillancesensorthealthtracking",
            name="recovery_type",
            field=models.CharField(
                blank=True,
                choices=[("automatic", "Automatic"), ("manual", "Manual")],
                help_text="Set when status='operational'. Null for failure transitions.",
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="surveillancesensorthealthtracking",
            name="recorded_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="SurveillanceHeartbeatEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dispatched_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "expected_at",
                    models.DateTimeField(
                        help_text="Scheduled dispatch time based on 1Hz cadence"
                    ),
                ),
                (
                    "delivered_on_time",
                    models.BooleanField(
                        default=True,
                        help_text="True if dispatch succeeded within the acceptable latency window",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heartbeat_events",
                        to="surveillance_monitoring_operations.surveillancesession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveillanceSensorFailureNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("previous_status", models.CharField(max_length=12)),
                ("new_status", models.CharField(max_length=12)),
                (
                    "recovery_type",
                    models.CharField(
                        blank=True,
                        help_text="Set only for operational recoveries",
                        max_length=12,
                        null=True,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failure_notifications",
                        to="surveillance_monitoring_operations.surveillancesensor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveillanceTrackEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dispatched_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "expected_at",
                    models.DateTimeField(
                        help_text="Scheduled dispatch time based on 1Hz cadence"
                    ),
                ),
                (
                    "had_active_tracks",
                    models.BooleanField(
                        default=False,
                        help_text="True if the fuser produced at least one track message this tick",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_events",
                        to="surveillance_monitoring_operations.surveillancesession",
                    ),
                ),
            ],
        ),
    ]
