# Generated by Django 5.1.5 on 2025-02-25 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_feed_operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightObeservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(help_text='Session ID for the stream')),
                ('latitude_dd', models.FloatField(help_text='Latitude of the observation')),
                ('longitude_dd', models.FloatField(help_text='Longitude of the observation')),
                ('altitude_mm', models.FloatField(help_text='Altitude of the observation')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Timestamp of the observation')),
                ('traffic_source', models.IntegerField(help_text='Traffic source of the observation')),
                ('source_type', models.IntegerField(help_text='Source type of the observation')),
                ('icao_address', models.TextField(help_text='ICAO address of the observation')),
                ('metadata', models.TextField(help_text='Raw data for the RID stream')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
