# Generated by Django 5.1.5 on 2025-03-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight_feed_operations", "0004_remove_flightobeservation_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightobeservation",
            name="session_id",
            field=models.UUIDField(blank=True, help_text="Session ID for the stream", null=True),
        ),
    ]
