# Generated by Django 5.1.8 on 2025-04-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_feed_operations', '0005_alter_flightobeservation_session_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlightObeservation',
            new_name='FlightObservation',
        ),
    ]
