# Generated by Django 5.2.8 on 2025-11-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_feed_operations", "0006_rename_flightobeservation_flightobservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightobservation",
            name="traffic_source",
            field=models.IntegerField(
                choices=[
                    (0, "1090ES"),
                    (1, "UAT"),
                    (2, "Multi-radar (MRT)"),
                    (3, "MLAT"),
                    (4, "SSR"),
                    (5, "PSR"),
                    (6, "Mode-S"),
                    (7, "MRT"),
                    (8, "SSR + PSR Fused"),
                    (9, "ADS-B"),
                    (10, "FLARM"),
                    (11, "Network Remote-ID"),
                    (12, "Other"),
                ],
                help_text="Source of the observation",
            ),
        ),
    ]
