# Generated by Django 5.1.5 on 2025-03-13 09:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ISASubscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("view", models.TextField(blank=True, help_text="The view box of the subscription", null=True)),
                ("flight_details", models.TextField(blank=True, help_text="All the flight details of the subscription", null=True)),
                ("end_datetime", models.DateTimeField(blank=True, help_text="The end datetime of the subscription", null=True)),
                ("view_hash", models.IntegerField(blank=True, db_index=True, help_text="The hash of the view box", max_length=255, null=True)),
                ("is_simulated", models.BooleanField(blank=True, default=False, help_text="Is this for a experimental", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
