# Generated by Django 5.1.5 on 2025-03-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rid_operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="isasubscription",
            name="view_hash",
            field=models.IntegerField(blank=True, db_index=True, help_text="The hash of the view box", null=True),
        ),
    ]
