# Generated by Django 5.1.5 on 2025-03-13 13:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rid_operations", "0002_alter_isasubscription_view_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="isasubscription",
            name="subscription_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text="The subscription ID generated by DSS"),
        ),
    ]
