from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol, runtime_checkable
from uuid import UUID

from flight_blender.domain_types.scd import (
    CompositeOperationalIntentPayload,
    OperationalIntentReferenceDSSResponse,
    OperationalIntentUSSDetails,
    PartialCreateOperationalIntentReference,
    SubscriberToNotify,
)


@runtime_checkable
class AsyncFlightDeclarationRepository(Protocol):
    """Async repository used by FastAPI handlers (``FlightDeclarationOperations``).

    Concrete implementation: ``SQLAlchemyFlightDeclarationRepository`` in
    ``flight_blender.infrastructure.database.repositories.sa_flight_declarations``.
    """

    async def create(self, **kwargs: Any) -> Any: ...
    async def get_by_id(self, declaration_id: UUID) -> Any | None: ...
    async def list(
        self,
        start_date: datetime | None = None,
        end_date: datetime | None = None,
        states: list[int] | None = None,
    ) -> list[Any]: ...
    async def update(self, declaration_id: UUID, **fields: Any) -> Any | None: ...
    async def add_state_history_entry(self, flight_declaration_id: UUID, original_state: int, new_state: int, notes: str = "") -> None: ...
    async def delete(self, declaration_id: UUID) -> bool: ...
    def serialize(self, obj: Any) -> dict: ...


@runtime_checkable
class SyncFlightDeclarationRepository(Protocol):
    """Sync DB surface used by Celery tasks and DSS dispatch.

    Concrete implementation: ``SyncDatabaseFacade`` in
    ``flight_blender.infrastructure.database.repositories.sync_facade``.
    """

    # peer ops
    def get_peer_operational_intent_details_by_id(self, operational_intent_id: str) -> Any | None: ...
    def get_peer_operational_intent_reference_by_id(self, operational_intent_reference_id: str) -> Any | None: ...
    def create_or_update_peer_operational_intent_details(
        self, peer_operational_intent_id: str, operational_intent_details: OperationalIntentUSSDetails
    ) -> Any | None: ...
    def create_or_update_peer_operational_intent_reference(
        self, peer_operational_intent_reference_id: str, peer_operational_intent_reference: OperationalIntentReferenceDSSResponse
    ) -> Any | None: ...
    def create_or_update_peer_composite_operational_intent(
        self, operation_id: str, composite_operational_intent: CompositeOperationalIntentPayload
    ) -> bool: ...
    def clear_stored_operational_intents(self) -> None: ...

    # flight declarations
    def get_all_flight_declarations(self) -> list: ...
    def check_flight_declaration_exists(self, flight_declaration_id: str) -> bool: ...
    def get_flight_declaration_by_id(self, flight_declaration_id: str) -> Any | None: ...
    def create_flight_declaration(self, flight_declaration_creation: Any) -> Any | None: ...
    def delete_flight_declaration(self, flight_declaration_id: str) -> bool: ...
    def set_flight_declaration_non_conforming(self, flight_declaration: Any) -> None: ...
    def check_flight_declaration_active(self, flight_declaration_id: str, now: datetime) -> bool: ...
    def check_active_activated_flights_exist(self) -> bool: ...
    def get_active_activated_flight_declarations(self) -> Any: ...
    def get_current_flight_accepted_activated_declaration_ids(self, now: str) -> Any: ...
    def update_telemetry_timestamp(self, flight_declaration_id: str) -> bool: ...
    def update_flight_operation_state(self, flight_declaration_id: str, state: int) -> bool: ...
    def update_flight_operation_operational_intent(
        self, flight_declaration_id: str, operational_intent: PartialCreateOperationalIntentReference
    ) -> bool: ...

    # composite operational intents
    def check_composite_operational_intent_exists(self, flight_declaration_id: str) -> bool: ...
    def get_composite_operational_intent_by_declaration_id(self, flight_declaration_id: str) -> Any | None: ...
    def create_or_update_composite_operational_intent(self, flight_declaration: Any, composite_operational_intent_payload: Any) -> bool: ...

    # operational intent references
    def get_flight_operational_intent_reference_by_flight_declaration_id(self, flight_declaration_id: str) -> Any | None: ...
    def get_flight_operational_intent_reference_by_flight_declaration_obj(self, flight_declaration: Any) -> Any | None: ...
    def check_flight_operational_intent_reference_by_id_exists(self, operational_intent_ref_id: str) -> bool: ...
    def get_operational_intent_reference_by_id(self, operational_intent_ref_id: str) -> Any: ...
    def get_flight_operational_intent_reference_by_id(self, operational_intent_ref_id: str) -> Any | None: ...
    def update_flight_operational_intent_reference_ovn(self, flight_operational_intent_reference: Any, ovn: str) -> bool: ...
    def update_flight_operational_intent_reference_op_int(
        self, flight_operational_intent_reference: Any, dss_operational_intent_reference_id: str
    ) -> bool: ...
    def update_flight_operational_intent_reference(
        self, flight_operational_intent_reference: Any, update_operational_intent_reference: OperationalIntentReferenceDSSResponse
    ) -> bool: ...
    def update_flight_operational_intent_reference_op_int_ovn(
        self, flight_operational_intent_reference: Any, dss_operational_intent_reference_id: str, ovn: str
    ) -> bool: ...
    def update_flight_operational_intent_reference_with_dss_response(
        self, flight_declaration: Any, dss_operational_intent_reference_id: str, ovn: str, dss_response: OperationalIntentReferenceDSSResponse
    ) -> bool: ...
    def create_flight_operational_intent_reference_with_submitted_operational_intent(
        self, flight_declaration: Any, operational_intent_reference_payload: Any
    ) -> Any | None: ...
    def create_flight_operational_intent_reference_from_flight_declaration_obj(self, flight_declaration: Any) -> bool: ...
    def create_flight_operational_intent_reference(
        self, flight_declaration: Any, created_operational_intent_reference: OperationalIntentReferenceDSSResponse
    ) -> Any: ...

    # subscribers
    def get_subscribers_of_operational_intent_reference(self, flight_operational_intent_reference: Any) -> Any: ...
    def create_flight_operational_intent_reference_subscribers(self, flight_declaration: Any, subscribers: list[SubscriberToNotify]) -> bool: ...

    # operational intent details
    def check_flight_operational_intent_details_by_id_exists(self, operational_intent_ref_id: str) -> bool: ...
    def get_operational_intent_details_by_flight_declaration(self, flight_declaration: Any) -> Any | None: ...
    def get_operational_intent_details_by_flight_declaration_id(self, declaration_id: str) -> Any | None: ...
    def create_flight_operational_intent_details_with_submitted_operational_intent(
        self, flight_declaration: Any, operational_intent_details_payload: OperationalIntentUSSDetails
    ) -> Any | None: ...
    def update_flight_operational_intent_details(
        self, flight_operational_intent_detail: Any, operational_intent_details: OperationalIntentUSSDetails
    ) -> bool: ...


@runtime_checkable
class SCDQueryClient(Protocol):
    """DSS Strategic Coordination query client used by flight-declaration ops.

    Concrete implementation: ``SCDOperations`` in
    ``flight_blender.infrastructure.dss.scd``.
    """

    def get_and_process_nearby_operational_intents(self, volumes: list[Any]) -> Any: ...


@runtime_checkable
class OperationalIntentParser(Protocol):
    """DSS operational-intent reference parser used by flight-declaration ops.

    Concrete implementation: ``OperationalIntentReferenceHelper`` in
    ``flight_blender.infrastructure.dss.scd``.
    """

    def parse_volume_to_volume4D(self, volume: dict) -> Any: ...


@runtime_checkable
class SCDNotificationDispatcher(Protocol):
    """Fire-and-forget DSS / notification dispatcher used by flight-declaration ops.

    Concrete implementation: Celery task adapters in
    ``flight_blender.infrastructure.celery.tasks.flight_declarations``.
    """

    def send_operational_update_message(self, flight_declaration_id: str, message_text: str, level: str) -> None: ...
    def submit_flight_declaration_to_dss_async(self, flight_declaration_id: str) -> None: ...
