from datetime import datetime
from typing import Any, Protocol, runtime_checkable
from uuid import UUID

from flight_blender.domain_types.surveillance import ActiveTrack, TrackMessage


@runtime_checkable
class TrackStore(Protocol):
    """Structural interface for the track persistence surface used by fusers.

    Concrete implementations (e.g. ``infrastructure.redis.stream_operations.RedisStreamOperations``)
    provide Redis-backed active-track storage. Core operations only see this Protocol.
    """

    def check_active_track_exists(self, session_id: str, unique_aircraft_identifier: str) -> bool: ...
    def get_active_track(self, session_id: str, unique_aircraft_identifier: str) -> ActiveTrack | None: ...
    def add_active_track_to_session(self, session_id: str, active_track: ActiveTrack) -> None: ...
    def update_active_track(self, session_id: str, active_track: ActiveTrack) -> None: ...
    def get_all_active_tracks_in_session(self, session_id: str) -> list[ActiveTrack]: ...


@runtime_checkable
class TrafficDataFuser(Protocol):
    """Structural interface for traffic data fusion implementations."""

    def generate_track_messages(self) -> list[TrackMessage]:
        """Run the full fusion pipeline and return track messages."""
        ...


@runtime_checkable
class SurveillanceRepository(Protocol):
    async def get_active_surveillance_sensors(self) -> Any: ...
    async def get_sensor_by_id(self, sensor_id: UUID) -> Any | None: ...
    async def get_session_by_id(self, session_id: UUID) -> Any | None: ...
    async def create_session(self, session_id: UUID, valid_until: datetime) -> bool: ...
    async def delete_session(self, session_id: UUID) -> None: ...
    async def get_all_active_sessions(self) -> Any: ...
    async def get_sessions_with_events_in_window(self, start_time: datetime, end_time: datetime) -> Any: ...
    async def get_sensor_health_record(self, sensor_id: UUID) -> Any | None: ...
    async def get_health_tracking_records_for_sensor(self, sensor_id: UUID, start_time: datetime, end_time: datetime) -> Any: ...
    async def get_sensor_status_before_time(self, sensor_id: UUID, before_time: datetime) -> str | None: ...
    async def get_heartbeat_events_for_session(self, session_id: UUID, start_time: datetime, end_time: datetime) -> Any: ...
    async def get_track_events_for_session(self, session_id: UUID, start_time: datetime, end_time: datetime) -> Any: ...
    async def get_failure_notifications_for_sensor(self, sensor_id: UUID, start_time: datetime, end_time: datetime) -> Any: ...
    async def get_all_failure_notifications(self, start_time: datetime, end_time: datetime) -> Any: ...
    async def update_sensor_health_status(self, sensor_id: UUID, new_status: str, recovery_type: str | None = None) -> bool: ...
    async def record_heartbeat_event(self, session_id: UUID, expected_at: datetime, delivered_on_time: bool) -> bool: ...
    async def record_track_event(self, session_id: UUID, expected_at: datetime, had_active_tracks: bool) -> bool: ...


@runtime_checkable
class SurveillanceTaskScheduler(Protocol):
    def schedule_surveillance_heartbeat(self, surveillance_session_id: str) -> bool: ...
    def schedule_surveillance_track(self, surveillance_session_id: str) -> bool: ...
    def cancel_session_tasks(self, session_id: str) -> None: ...
