from typing import Any, Protocol, runtime_checkable
from uuid import UUID


@runtime_checkable
class AsyncConstraintRepository(Protocol):
    async def get_constraint_detail_by_id(self, constraint_id: UUID) -> Any | None: ...
    async def get_constraint_details(self) -> Any: ...
    async def get_constraint_reference_by_id(self, ref_id: UUID) -> Any | None: ...
    async def get_constraint_references(self) -> Any: ...
    async def create_constraint_detail(self, **kwargs: Any) -> Any: ...
    async def create_constraint_reference(self, **kwargs: Any) -> Any: ...
    async def create_composite_constraint(self, **kwargs: Any) -> Any: ...


@runtime_checkable
class ConstraintRepository(Protocol):
    def check_constraint_id_exists(self, constraint_id: str) -> bool: ...
    def get_constraint_by_geofence(self, geofence: Any) -> Any: ...
    def check_constraint_reference_id_exists(self, constraint_reference_id: str) -> bool: ...
    def get_constraint_reference_by_id(self, constraint_reference_id: str) -> Any: ...
    def get_constraint_details(self, constraint_id: str) -> Any: ...
    def get_geofence_by_constraint_reference_id(self, constraint_reference_id: str) -> Any | None: ...
    def write_constraint_details(self, constraint_id: str, constraint: Any) -> bool: ...
    def write_constraint_reference_details(self, constraint: Any) -> bool: ...
    def create_or_update_composite_constraint(self, composite_constraint_payload: Any) -> Any: ...
    def update_constraint_reference_ovn(self, constraint_reference: Any, ovn: str) -> bool: ...
    def create_or_update_constraint_detail(self, constraint: Any, geofence: Any) -> Any | None: ...
    def create_or_update_constraint_reference(self, constraint_reference: Any, geofence: Any, flight_declaration: Any) -> Any | None: ...
