# Generated by Django 5.1.5 on 2025-03-13 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geo_fence_operations", "0003_geofence_message_geofence_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="geofence",
            options={"ordering": ["-created_at"]},
        ),
    ]
