# Generated by Django 5.1.8 on 2025-05-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_fence_operations', '0004_alter_geofence_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofence',
            name='altitude_ref',
            field=models.IntegerField(choices=[(0, 'WGS84'), (1, 'AGL'), (2, 'MSL'), (4, 'W84')], default=0),
        ),
    ]
