# Generated by Django 5.1.8 on 2025-04-25 11:45

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraint_operations', '0001_initial'),
        ('geo_fence_operations', '0004_alter_geofence_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstraintDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('volumes', models.TextField(blank=True)),
                ('_type', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geofence', models.OneToOneField(blank=True, help_text='Reference to the geofence associated with the constraint.', null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_fence_operations.geofence')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Constraint',
        ),
        migrations.RemoveField(
            model_name='constraintreference',
            name='details',
        ),
        migrations.AddField(
            model_name='constraintreference',
            name='geofence',
            field=models.OneToOneField(blank=True, help_text='Reference to the geofence associated with the constraint.', null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_fence_operations.geofence'),
        ),
        migrations.AddField(
            model_name='constraintreference',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Set to true if the operational intent is live'),
        ),
        migrations.AddField(
            model_name='constraintreference',
            name='manager',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='constraintreference',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='constraintreference',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='constraintreference',
            name='uss_availability',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='constraintreference',
            name='uss_base_url',
            field=models.CharField(blank=True, help_text='USS base URL', max_length=256),
        ),
        migrations.AddField(
            model_name='constraintreference',
            name='version',
            field=models.CharField(blank=True, help_text='Constraint version', max_length=256),
        ),
    ]
