# Generated by Django 5.1.8 on 2025-05-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraint_operations', '0003_alter_constraintreference_ovn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraintdetail',
            name='_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
