# Generated by Django 5.1.8 on 2025-05-20 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraint_operations', '0004_alter_constraintdetail__type'),
        ('flight_declaration_operations', '0015_alter_flightoperationalintentreference_ovn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraintreference',
            name='flight_declaration',
            field=models.ForeignKey(blank=True, help_text='Reference to the flight declaration associated with the constraint.', null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_declaration_operations.flightdeclaration'),
        ),
    ]
