# Generated by Django 5.2.8 on 2025-11-17 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance_monitoring_operations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveillanceSensor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sensor_type",
                    models.IntegerField(
                        choices=[
                            (0, "1090ES"),
                            (1, "UAT"),
                            (2, "Multi-radar (MRT)"),
                            (3, "MLAT"),
                            (4, "SSR"),
                            (5, "PSR"),
                            (6, "Mode-S"),
                            (7, "MRT"),
                            (8, "SSR + PSR Fused"),
                            (9, "ADS-B"),
                            (10, "FLARM"),
                            (11, "Network Remote-ID"),
                            (12, "Other"),
                        ],
                        default=12,
                    ),
                ),
                (
                    "sensor_identifier",
                    models.CharField(
                        help_text="Describe the sensor, e.g., serial number or detailed location",
                        max_length=256,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
