# Generated by Django 5.2.10 on 2026-04-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance_monitoring_operations", "0006_sdsp_metrics_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveillancesensor",
            name="sensor_type",
            field=models.IntegerField(
                choices=[
                    (0, "1090ES"),
                    (1, "UAT"),
                    (2, "Multi-radar (MRT)"),
                    (3, "MLAT"),
                    (4, "SSR"),
                    (5, "PSR"),
                    (6, "Mode-S"),
                    (7, "MRT"),
                    (8, "SSR + PSR Fused"),
                    (9, "ADS-B"),
                    (10, "FLARM"),
                    (11, "Network Remote-ID"),
                    (12, "Other"),
                    (13, "Broadcast Remote-ID"),
                    (14, "ADS-L"),
                    (15, "Drone sensed by another means"),
                ],
                default=12,
            ),
        ),
    ]
