name: Linting
on: [push]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v3
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: codespell-project/actions-codespell@v2
        with:
          ignore_words_file: .codespellignore
          exclude_file: "**/redis.conf"
  pytest:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "sqlite://:memory:"
      BYPASS_AUTH_TOKEN_VERIFICATION: "1"
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --dev
      - name: Run tests with pytest
        run: |
          uv run pytest