# Generated by Django 5.1.8 on 2025-05-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_declaration_operations', '0014_peercompositeoperationalintent_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightoperationalintentreference',
            name='ovn',
            field=models.CharField(blank=True, help_text='Once the operational intent is created, the OVN is stored here.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='peeroperationalintentreference',
            name='ovn',
            field=models.CharField(blank=True, help_text='Once the operational intent is created, the OVN is stored here.', max_length=128, null=True),
        ),
    ]
