# Generated by Django 5.1.5 on 2025-02-25 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformance_monitoring_operations', '0001_initial'),
        ('flight_declaration_operations', '0009_alter_flightdeclaration_type_of_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskscheduler',
            name='session_id',
            field=models.UUIDField(blank=True, help_text='The session id that this task is associated with this task scheduler', null=True),
        ),
        migrations.AlterField(
            model_name='taskscheduler',
            name='flight_declaration',
            field=models.OneToOneField(blank=True, help_text='The flight declaration that this task is associated with this task scheduler', null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_declaration_operations.flightdeclaration'),
        ),
    ]
