# Generated by Django 5.2.8 on 2025-11-27 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conformance_monitoring_operations", "0002_taskscheduler_session_id_and_more"),
        (
            "flight_declaration_operations",
            "0015_alter_flightoperationalintentreference_ovn_and_more",
        ),
        ("geo_fence_operations", "0005_alter_geofence_altitude_ref"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConformanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        editable=False,
                        help_text="Unique identifier for the conformance record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conformance_state",
                    models.IntegerField(
                        choices=[(0, "Nonconforming"), (1, "Conforming")],
                        help_text="The conformance state of the flight declaration at the time of the record",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the conformance record was created",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the conformance event (deviation or rectification)"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("deviation", "Deviation"),
                            ("rectification", "Rectification"),
                        ],
                        help_text="Type of conformance event: deviation or rectification",
                        max_length=20,
                    ),
                ),
                (
                    "geofence_breach",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the event involved a geofence breach",
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the conformance issue has been resolved",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the conformance record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the conformance record was last updated",
                    ),
                ),
                (
                    "flight_declaration",
                    models.ForeignKey(
                        help_text="The flight declaration associated with this conformance record",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flight_declaration_operations.flightdeclaration",
                    ),
                ),
                (
                    "geofence",
                    models.ForeignKey(
                        blank=True,
                        help_text="The geofence involved in the event, if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="geo_fence_operations.geofence",
                    ),
                ),
            ],
        ),
    ]
