# Generated by Django 5.2.8 on 2025-12-01 16:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conformance_monitoring_operations", "0003_conformancerecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conformancerecord",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the conformance record",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
